# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bimestres.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_bimestre(object):
    def setupUi(self, bimestre):
        bimestre.setObjectName("bimestre")
        bimestre.resize(533, 570)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Transferências/9056986_if_design_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bimestre.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(bimestre)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 371, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Transferências/transferir.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 127, 191, 21))
        self.label_2.setObjectName("label_2")
        self.combo_bimestre = QtWidgets.QComboBox(self.centralwidget)
        self.combo_bimestre.setGeometry(QtCore.QRect(244, 198, 101, 23))
        self.combo_bimestre.setObjectName("combo_bimestre")
        self.combo_bimestre.addItem("")
        self.combo_bimestre.addItem("")
        self.botao_confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_confirmar.setGeometry(QtCore.QRect(210, 394, 131, 30))
        self.botao_confirmar.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Transferências/1891021_approved_check_checkbox_checkmark_confirm_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_confirmar.setIcon(icon1)
        self.botao_confirmar.setCheckable(False)
        self.botao_confirmar.setAutoRepeat(True)
        self.botao_confirmar.setAutoExclusive(True)
        self.botao_confirmar.setObjectName("botao_confirmar")
        self.M_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.M_1.setGeometry(QtCore.QRect(236, 240, 120, 20))
        self.M_1.setObjectName("M_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 381, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 191, 16))
        self.label_4.setObjectName("label_4")
        self.M_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.M_4.setGeometry(QtCore.QRect(237, 330, 120, 20))
        self.M_4.setObjectName("M_4")
        self.M_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.M_3.setGeometry(QtCore.QRect(236, 300, 120, 20))
        self.M_3.setObjectName("M_3")
        self.M_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.M_2.setGeometry(QtCore.QRect(236, 270, 120, 20))
        self.M_2.setObjectName("M_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 240, 161, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 270, 161, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(69, 300, 161, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(69, 331, 161, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 384, 201, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(350, 384, 191, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 440, 80, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(129, 500, 221, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(140, 470, 70, 15))
        self.label_13.setObjectName("label_13")
        self.M_final = QtWidgets.QLineEdit(self.centralwidget)
        self.M_final.setGeometry(QtCore.QRect(224, 440, 151, 23))
        self.M_final.setObjectName("M_final")
        self.situa = QtWidgets.QLineEdit(self.centralwidget)
        self.situa.setGeometry(QtCore.QRect(224, 470, 151, 23))
        self.situa.setObjectName("situa")
        self.N_prova_final = QtWidgets.QLineEdit(self.centralwidget)
        self.N_prova_final.setGeometry(QtCore.QRect(354, 498, 100, 20))
        self.N_prova_final.setObjectName("N_prova_final")
        self.botao_sobre = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sobre.setGeometry(QtCore.QRect(430, 530, 80, 23))
        self.botao_sobre.setObjectName("botao_sobre")
        bimestre.setCentralWidget(self.centralwidget)

        self.retranslateUi(bimestre)
        QtCore.QMetaObject.connectSlotsByName(bimestre)
        bimestre.setFixedSize(bimestre.width(), bimestre.height()) #retira a função de tela cheia
        self.M_3.setEnabled(False)
        self.M_4.setEnabled(False)
        self.combo_bimestre.currentIndexChanged.connect(self.modificar_campos)
        self.botao_confirmar.clicked.connect(self.calcular)
        self.botao_sobre.clicked.connect(self.mostrar_sobre)

    def mostrar_sobre(self):
        # essa função ira importa um outro codigo que será o "sobre"
        from Sobre import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.sobre = Ui_MainWindow()
        self.sobre.setupUi(self.janela)
        self.janela.show()


    def modificar_campos(self):
        if int(self.combo_bimestre.currentText()) == 2: #currenttext vai pegar o valor que estiver na combo box
            self.M_3.setEnabled(False)# desabilitar o campo 3
            self.M_4.setEnabled(False)# desabilitar o campo 4
        else:
            self.M_3.setEnabled(True)# habilitar o campo 3
            self.M_4.setEnabled(True)# habilitar o campo 4
    def calcular(self):
        # metodo de proteção contra erros no codigo
        mensagem = QMessageBox() # tela de mensagem de erro
        mensagem.setIcon(QMessageBox.Critical)  # mensagem de erro
        mensagem.setWindowTitle("erro")
        #
        op = int(self.combo_bimestre.currentText()) #currentText pega o valor que esta na combobox
        if op == 2: # opção 2 bimestres
            try:
                num1 = int(self.M_1.text())
                num2 = int(self.M_2.text())
                media = int((num1 * 2 + num2 * 3) / 5 )
                self.M_final.setText(str(media))

                if media >= 60:
                    self.situa.setText("Aprovado! ")
                elif media < 40:
                    self.situa.setText("Reprovado! ")
                else:
                    self.situa.setText("Em Recuperação! ")

                if media >= 40 and media < 60:
                    notaF = 120 - media
                    self.N_prova_final.setText(str(notaF))
                else:
                    self.N_prova_final.setText("")
            except ValueError:
                mensagem.setText("Número incorretos!")
                mensagem.exec()
        else:   #opção 4 bimestres
            try:
                num1 = int(self.M_1.text())
                num2 = int(self.M_2.text())
                num3 = int(self.M_3.text())
                num4 = int(self.M_4.text())
                media = int((num1 * 2 + num2 * 2 + num3 * 3 + num4 * 3) / 10 )
                self.M_final.setText(str(media))

                if media >= 60:
                    self.situa.setText("Aprovado! ")
                elif media < 40:
                    self.situa.setText("Reprovado! ")
                else:
                    self.situa.setText("Em Recuperação! ")

                if media >= 40 and media < 60:
                    notaF = 120 - media
                    self.N_prova_final.setText(str(notaF))
                else:
                    self.N_prova_final.setText("")
            except ValueError:
                mensagem.setText("Número incorretos!")
                mensagem.exec()



    def retranslateUi(self, bimestre):
        _translate = QtCore.QCoreApplication.translate
        bimestre.setWindowTitle(_translate("bimestre", "IFRN-BIMESTRES"))
        self.label_2.setText(_translate("bimestre", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Calculadora IFRN</span></p></body></html>"))
        self.combo_bimestre.setItemText(0, _translate("bimestre", "2"))
        self.combo_bimestre.setItemText(1, _translate("bimestre", "4"))
        self.botao_confirmar.setText(_translate("bimestre", "Confirmar"))
        self.label_3.setText(_translate("bimestre", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ff0000;\">Os Números digitados utilizando a notação entre 0 a 100</span></p></body></html>"))
        self.label_4.setText(_translate("bimestre", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">Quantidade de Bimestres:</span></p></body></html>"))
        self.label_5.setText(_translate("bimestre", "Media do 1° bimestre:"))
        self.label_6.setText(_translate("bimestre", "Media do 2° Bimestre: "))
        self.label_7.setText(_translate("bimestre", "Media do 3° bimestre:"))
        self.label_8.setText(_translate("bimestre", "Media do 4° Bimestre:"))
        self.label_9.setText(_translate("bimestre", "<html><head/><body><p><span style=\" font-size:20pt;\">------------------------------------</span></p></body></html>"))
        self.label_10.setText(_translate("bimestre", "<html><head/><body><p><span style=\" font-size:20pt;\">------------------------------------</span></p></body></html>"))
        self.label_11.setText(_translate("bimestre", "Media Final:"))
        self.label_12.setText(_translate("bimestre", "Nota Necessaria pra Prova Final:"))
        self.label_13.setText(_translate("bimestre", "Situação:"))
        self.botao_sobre.setText(_translate("bimestre", "Sobre"))


if __name__ == "__main__":
    import sys
    app =QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_bimestre()
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())