# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(367, 457)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(18)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Transferências/cacu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setEnabled(True)
        self.gridWidget.setGeometry(QtCore.QRect(0, 74, 361, 381))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.gridWidget.setFont(font)
        self.gridWidget.setMouseTracking(False)
        self.gridWidget.setStyleSheet("\n"
"")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.engual = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.engual.sizePolicy().hasHeightForWidth())
        self.engual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.engual.setFont(font)
        self.engual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.engual.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: oblique 28pt \"Sans Serif\";\n"
"    background-color: rgb(159, 159, 159);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.engual.setObjectName("engual")
        self.gridLayout.addWidget(self.engual, 5, 3, 1, 1)
        self.botao_1 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_1.sizePolicy().hasHeightForWidth())
        self.botao_1.setSizePolicy(sizePolicy)
        self.botao_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_1.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_1.setObjectName("botao_1")
        self.gridLayout.addWidget(self.botao_1, 1, 0, 1, 1)
        self.botao_3 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_3.sizePolicy().hasHeightForWidth())
        self.botao_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_3.setFont(font)
        self.botao_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_3.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_3.setObjectName("botao_3")
        self.gridLayout.addWidget(self.botao_3, 1, 2, 1, 1)
        self.botao_2 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_2.sizePolicy().hasHeightForWidth())
        self.botao_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.botao_2.setFont(font)
        self.botao_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_2.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_2.setObjectName("botao_2")
        self.gridLayout.addWidget(self.botao_2, 1, 1, 1, 1)
        self.botao_delete = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_delete.sizePolicy().hasHeightForWidth())
        self.botao_delete.setSizePolicy(sizePolicy)
        self.botao_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_delete.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(159, 159, 159);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_delete.setObjectName("botao_delete")
        self.gridLayout.addWidget(self.botao_delete, 0, 2, 1, 1)
        self.soma = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.soma.sizePolicy().hasHeightForWidth())
        self.soma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.soma.setFont(font)
        self.soma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.soma.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: oblique 28pt \"Sans Serif\";\n"
"    background-color: rgb(159, 159, 159);\n"
"\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.soma.setObjectName("soma")
        self.gridLayout.addWidget(self.soma, 4, 3, 1, 1)
        self.botao_4 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_4.sizePolicy().hasHeightForWidth())
        self.botao_4.setSizePolicy(sizePolicy)
        self.botao_4.setMinimumSize(QtCore.QSize(0, 34))
        self.botao_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_4.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_4.setObjectName("botao_4")
        self.gridLayout.addWidget(self.botao_4, 2, 0, 2, 1)
        self.virgula = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.virgula.sizePolicy().hasHeightForWidth())
        self.virgula.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.virgula.setFont(font)
        self.virgula.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.virgula.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.virgula.setObjectName("virgula")
        self.gridLayout.addWidget(self.virgula, 5, 2, 1, 1)
        self.botao_7 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_7.sizePolicy().hasHeightForWidth())
        self.botao_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_7.setFont(font)
        self.botao_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_7.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_7.setObjectName("botao_7")
        self.gridLayout.addWidget(self.botao_7, 4, 0, 1, 1)
        self.divisao = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.divisao.sizePolicy().hasHeightForWidth())
        self.divisao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.divisao.setFont(font)
        self.divisao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.divisao.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: oblique 28pt \"Sans Serif\";\n"
"    background-color: rgb(159, 159, 159);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.divisao.setObjectName("divisao")
        self.gridLayout.addWidget(self.divisao, 0, 3, 1, 1)
        self.botao_8 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_8.sizePolicy().hasHeightForWidth())
        self.botao_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_8.setFont(font)
        self.botao_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_8.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_8.setObjectName("botao_8")
        self.gridLayout.addWidget(self.botao_8, 4, 1, 1, 1)
        self.menos = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menos.sizePolicy().hasHeightForWidth())
        self.menos.setSizePolicy(sizePolicy)
        self.menos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menos.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: oblique 28pt \"Sans Serif\";\n"
"    background-color: rgb(159, 159, 159);\n"
"\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.menos.setObjectName("menos")
        self.gridLayout.addWidget(self.menos, 2, 3, 2, 1)
        self.botao_6 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_6.sizePolicy().hasHeightForWidth())
        self.botao_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_6.setFont(font)
        self.botao_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_6.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_6.setObjectName("botao_6")
        self.gridLayout.addWidget(self.botao_6, 2, 2, 1, 1)
        self.botao_9 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_9.sizePolicy().hasHeightForWidth())
        self.botao_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_9.setFont(font)
        self.botao_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_9.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_9.setObjectName("botao_9")
        self.gridLayout.addWidget(self.botao_9, 4, 2, 1, 1)
        self.botao_0 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_0.sizePolicy().hasHeightForWidth())
        self.botao_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.botao_0.setFont(font)
        self.botao_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_0.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_0.setObjectName("botao_0")
        self.gridLayout.addWidget(self.botao_0, 5, 0, 1, 2)
        self.botao_clear = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_clear.sizePolicy().hasHeightForWidth())
        self.botao_clear.setSizePolicy(sizePolicy)
        self.botao_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_clear.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(159, 159, 159);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238,238)\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_clear.setObjectName("botao_clear")
        self.gridLayout.addWidget(self.botao_clear, 0, 0, 1, 2)
        self.botao_5 = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.botao_5.sizePolicy().hasHeightForWidth())
        self.botao_5.setSizePolicy(sizePolicy)
        self.botao_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_5.setStyleSheet("QPushButton{\n"
"font: italic 22pt \"Sans Serif\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(61, 61, 61);\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.botao_5.setObjectName("botao_5")
        self.gridLayout.addWidget(self.botao_5, 2, 1, 1, 1)
        self.multiplicacao = QtWidgets.QPushButton(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.multiplicacao.sizePolicy().hasHeightForWidth())
        self.multiplicacao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.multiplicacao.setFont(font)
        self.multiplicacao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.multiplicacao.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: oblique 28pt \"Sans Serif\";\n"
"    background-color: rgb(159, 159, 159);\n"
"\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushBotton{\n"
"background-color: rgb(208, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.multiplicacao.setObjectName("multiplicacao")
        self.gridLayout.addWidget(self.multiplicacao, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(8, -6, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())  # retira a função de tela cheia
        # configurando os botões da interface
        self.botao_0.clicked.connect(self.method_0)
        self.botao_1.clicked.connect(self.method_1)
        self.botao_2.clicked.connect(self.method_2)
        self.botao_3.clicked.connect(self.method_3)
        self.botao_4.clicked.connect(self.method_4)
        self.botao_5.clicked.connect(self.method_5)
        self.botao_6.clicked.connect(self.method_6)
        self.botao_7.clicked.connect(self.method_7)
        self.botao_8.clicked.connect(self.method_8)
        self.botao_9.clicked.connect(self.method_9)
        self.virgula.clicked.connect(self.method_virgula)
        self.botao_clear.clicked.connect(self.method_clear)
        self.botao_delete.clicked.connect(self.method_delete)
        self.engual.clicked.connect(self.method_engual)
        self.divisao.clicked.connect(self.method_divisao)
        self.multiplicacao.clicked.connect(self.method_multiplicacao)
        self.menos.clicked.connect(self.method_menos)
        self.soma.clicked.connect(self.method_soma)

    # funções a ser utilizadas na interface
    def method_0(self):
            txt = self.label.text()
            self.label.setText(txt + "0")

    def method_1(self):
            txt = self.label.text()
            self.label.setText(txt + "1")

    def method_2(self):
            txt = self.label.text()
            self.label.setText(txt + "2")

    def method_3(self):
            txt = self.label.text()
            self.label.setText(txt + "3")

    def method_4(self):
            txt = self.label.text()
            self.label.setText(txt + "4")

    def method_5(self):
            txt = self.label.text()
            self.label.setText(txt + "5")

    def method_6(self):
            txt = self.label.text()
            self.label.setText(txt + "6")

    def method_7(self):
            txt = self.label.text()
            self.label.setText(txt + "7")

    def method_8(self):
            txt = self.label.text()
            self.label.setText(txt + "8")

    def method_9(self):
            txt = self.label.text()
            self.label.setText(txt + "9")

    def method_virgula(self):
            txt = self.label.text()
            self.label.setText(txt + ",")

    def method_divisao(self):
            txt = self.label.text()
            self.label.setText(txt + "/")

    def method_multiplicacao(self):
            txt = self.label.text()
            self.label.setText(txt + "*")

    def method_menos(self):
            txt = self.label.text()
            self.label.setText(txt + "-")

    def method_soma(self):
            txt = self.label.text()
            self.label.setText(txt + "+")

    def method_clear(self):
            self.label.setText("")

    def method_delete(self):  # apaga os textos 1 por 1
            txt = self.label.text()
            self.label.setText(txt[:len(txt) - 1])

    def method_engual(self):
            txt = self.label.text()
            try:
                    ans = eval(txt)  # eval e uma função para executar as contas de forma rapida
                    self.label.setText(str(ans))
            except:
                    self.label.setText("erro")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.engual.setText(_translate("MainWindow", "="))
        self.engual.setShortcut(_translate("MainWindow", "enter"))
        self.botao_1.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:22pt; font-weight:400; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.botao_1.setText(_translate("MainWindow", "1"))
        self.botao_1.setShortcut(_translate("MainWindow", "1"))
        self.botao_3.setText(_translate("MainWindow", "3"))
        self.botao_3.setShortcut(_translate("MainWindow", "3"))
        self.botao_2.setText(_translate("MainWindow", "2"))
        self.botao_2.setShortcut(_translate("MainWindow", "2"))
        self.botao_delete.setText(_translate("MainWindow", "Delete"))
        self.botao_delete.setShortcut(_translate("MainWindow", "Backspace"))
        self.soma.setText(_translate("MainWindow", "+"))
        self.soma.setShortcut(_translate("MainWindow", "+"))
        self.botao_4.setText(_translate("MainWindow", "4"))
        self.botao_4.setShortcut(_translate("MainWindow", "4"))
        self.virgula.setText(_translate("MainWindow", "."))
        self.virgula.setShortcut(_translate("MainWindow", "."))
        self.botao_7.setText(_translate("MainWindow", "7"))
        self.botao_7.setShortcut(_translate("MainWindow", "7"))
        self.divisao.setText(_translate("MainWindow", "÷"))
        self.divisao.setShortcut(_translate("MainWindow", "/"))
        self.botao_8.setText(_translate("MainWindow", "8"))
        self.botao_8.setShortcut(_translate("MainWindow", "8"))
        self.menos.setText(_translate("MainWindow", "-"))
        self.menos.setShortcut(_translate("MainWindow", "-"))
        self.botao_6.setText(_translate("MainWindow", "6"))
        self.botao_6.setShortcut(_translate("MainWindow", "6"))
        self.botao_9.setText(_translate("MainWindow", "9"))
        self.botao_9.setShortcut(_translate("MainWindow", "9"))
        self.botao_0.setText(_translate("MainWindow", "0"))
        self.botao_0.setShortcut(_translate("MainWindow", "0"))
        self.botao_clear.setText(_translate("MainWindow", "Clear"))
        self.botao_clear.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.botao_5.setText(_translate("MainWindow", "5"))
        self.botao_5.setShortcut(_translate("MainWindow", "5"))
        self.multiplicacao.setText(_translate("MainWindow", "*"))
        self.multiplicacao.setShortcut(_translate("MainWindow", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
