# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object): #aqui
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 198)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 15, 371, 20))
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.temp = QtWidgets.QLineEdit(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(170, 65, 113, 23))
        self.temp.setObjectName("temp")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(90, 115, 80, 23))
        self.confirmar.setObjectName("confirmar")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 115, 80, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(78, 67, 101, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())# ele tira a função de tela cheia
        self.confirmar.clicked.connect(self.converte)# criando a função do botão
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "conversor de temperatra fahrenheit F° pra celsius C°"))
        self.confirmar.setText(_translate("MainWindow", "confirmar"))
        self.pushButton_2.setText(_translate("MainWindow", "sair"))
        self.label_2.setText(_translate("MainWindow", "Temperatura:"))
    def converte(self):#  função
        temp = int(self.temp.text())
        temp = (temp-32) * 5/9
        msg = QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle("Sucesso!")
        msg.setText("Resultado: "+str(temp)+"c°")
        msg.exec()

if __name__ == "__main__": #metodo para inicializar o programa
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow() # aqui tem que ter o nome da classe lá de cima, a primeira no caso
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())