# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Separador.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Separador(object):
    def setupUi(self, Separador):
        Separador.setObjectName("Separador")
        Separador.resize(303, 409)
        self.centralwidget = QtWidgets.QWidget(Separador)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 231, 61))
        self.label_4.setStyleSheet("font: italic 12pt \"Sans Serif\";")
        self.label_4.setObjectName("label_4")
        Separador.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Separador)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 20))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        Separador.setMenuBar(self.menubar)
        self.actionNovo = QtWidgets.QAction(Separador)
        self.actionNovo.setObjectName("actionNovo")
        self.actionAbrir = QtWidgets.QAction(Separador)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSair = QtWidgets.QAction(Separador)
        self.actionSair.setStatusTip("")
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(Separador)
        self.actionSobre.setObjectName("actionSobre")
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionSobre)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(Separador)
        QtCore.QMetaObject.connectSlotsByName(Separador)
        Separador.setFixedSize(Separador.width(), Separador.height())
    def retranslateUi(self, Separador):
        _translate = QtCore.QCoreApplication.translate
        Separador.setWindowTitle(_translate("Separador", "Separador"))
        self.label_4.setText(_translate("Separador", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">Sistema CAP</span></p></body></html>"))
        self.menuArquivo.setTitle(_translate("Separador", "Arquivo"))
        self.menuAjuda.setTitle(_translate("Separador", "Ajuda"))
        self.actionNovo.setText(_translate("Separador", "Novo"))
        self.actionNovo.setShortcut(_translate("Separador", "Ctrl+A"))
        self.actionAbrir.setText(_translate("Separador", "Abrir"))
        self.actionAbrir.setShortcut(_translate("Separador", "Ctrl+S"))
        self.actionSair.setText(_translate("Separador", "Sair"))
        self.actionSair.setShortcut(_translate("Separador", "Esc"))
        self.actionSobre.setText(_translate("Separador", "Sobre"))
        self.actionSobre.setShortcut(_translate("Separador", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QMainWindow()
    ui = Ui_Separador()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())