# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(44, 10, 321, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../Transferências/transferir.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(97, 149, 241, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(171, 171, 71, 16))
        self.label_3.setObjectName("label_3")
        self.Voltar = QtWidgets.QPushButton(self.centralwidget)
        self.Voltar.setGeometry(QtCore.QRect(157, 230, 101, 31))
        self.Voltar.setObjectName("Voltar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Voltar.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())  # retira a função de tela cheia

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sobre"))
        self.label_2.setText(_translate("MainWindow", "Desenvolvido por João Lourenço"))
        self.label_3.setText(_translate("MainWindow", "Versão 1.0"))
        self.Voltar.setText(_translate("MainWindow", "Voltar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())