# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMC.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 282)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 150, 201, 31))
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"")

        self.label.setObjectName("label")
        self.camponome = QtWidgets.QLineEdit(self.centralwidget)
        self.camponome.setGeometry(QtCore.QRect(190, 160, 113, 20))
        self.camponome.setObjectName("camponome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 181, 31))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 235, 181, 16))
        self.label_3.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.campoaltura = QtWidgets.QLineEdit(self.centralwidget)
        self.campoaltura.setGeometry(QtCore.QRect(190, 196, 113, 20))
        self.campoaltura.setObjectName("campoaltura")
        self.campoaltura_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.campoaltura_2.setGeometry(QtCore.QRect(190, 233, 113, 20))
        self.campoaltura_2.setObjectName("campoaltura_2")
        self.calcular = QtWidgets.QPushButton(self.centralwidget)
        self.calcular.setGeometry(QtCore.QRect(350, 220, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.calcular.setFont(font)
        self.calcular.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Transferências/iconfinder/326561_box_check_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calcular.setIcon(icon)
        self.calcular.setObjectName("calcular")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 10, 401, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../../Transferências/iconfinder/transferir.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.calcular.clicked.connect(self.IMC)

    def IMC(self):
        msg = QMessageBox()
        try:
            nome = self.camponome.text()
            altura = float(self.campoaltura.text())
            if altura < 10:
                pass
            else:
                altura = altura/100
            peso = float(self.campoaltura_2.text())
            cal = peso // (altura**2)
            cal = round(cal,2)
            resul = ""
            if cal < 18.5:
                resul = f"{cal} está abaixo do peso normal! "
            elif cal >= 18.5 and cal <= 24.9:
                resul = f"{cal} está com peso normal! "
            elif cal >= 25 and cal <= 29.9:
                resul = f"{cal} está em excesso de peso! "
            elif cal >= 30 and cal <= 34.9:
                resul = f"{cal} está com Obesidade classe I! "
            elif cal >= 35 and cal <= 39.9:
                resul = f"{cal} está com Obesidade classe II! "
            elif cal >= 40:
                resul = f"{cal} está com Obesidade classe III! "

            msg.setWindowTitle("IMC")
            msg.setIcon(QMessageBox.Information)
            msg.setText(f"{nome} seu IMC é {str(resul)}")
            msg.exec()
        except Exception as e:
            msg.setWindowTitle("Error")
            msg.setIcon(QMessageBox.Critical)
            msg.setText(str(e))
            msg.exec()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CALCULADORA IMC IFRN"))
        self.label.setText(_translate("MainWindow", "Digite o nome da pessoa:"))
        self.label_2.setText(_translate("MainWindow", "Digite a altura da pessoa:"))
        self.label_3.setText(_translate("MainWindow", "Digite o peso da pessoa: "))
        self.calcular.setText(_translate("MainWindow", "Calcular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())